export const enum ErrorCodes {
  ValidationError = "validation_error",
  BadRequest = "bad_request",
  Unauthorized = "unauthorized",
  PaymentRequired = "payment_required",
  Forbidden = "forbidden",
  NotFound = "not_found",
  MethodNotAllowed = "method_not_allowed",
  NotAcceptable = "not_acceptable",
  ProxyAuthenticationRequired = "proxy_authentication_required",
  RequestTimeout = "request_timeout",
  Conflict = "conflict",
  Gone = "gone",
  LengthRequired = "length_required",
  PreconditionFailed = "precondition_failed",
  PayloadTooLarge = "payload_too_large",
  UriTooLong = "uri_too_long",
  UnsupportedMediaType = "unsupported_media_type",
  RequestedRangeNotSatisfiable = "requested_range_not_satisfiable",
  ExpectationFailed = "expectation_failed",
  IAmATeapot = "i_am_a_teapot",
  Misdirected = "misdirected",
  UnprocessableEntity = "unprocessable_entity",
  FailedDependency = "failed_dependency",
  PreconditionRequired = "precondition_required",
  TooManyRequests = "too_many_requests",
  InternalServerError = "internal_server_error",
  NotImplemented = "not_implemented",
  BadGateway = "bad_gateway",
  ServiceUnavailable = "service_unavailable",
  GatewayTimeout = "gateway_timeout",
  HttpVersionNotSupported = "http_version_not_supported",
}

export const MAP_STATUS_CODE_TO_ERROR_CODE: Record<number, ErrorCodes> = {
  400: ErrorCodes.BadRequest,
  401: ErrorCodes.Unauthorized,
  402: ErrorCodes.PaymentRequired,
  403: ErrorCodes.Forbidden,
  404: ErrorCodes.NotFound,
  405: ErrorCodes.MethodNotAllowed,
  406: ErrorCodes.NotAcceptable,
  407: ErrorCodes.ProxyAuthenticationRequired,
  408: ErrorCodes.RequestTimeout,
  409: ErrorCodes.Conflict,
  410: ErrorCodes.Gone,
  411: ErrorCodes.LengthRequired,
  412: ErrorCodes.PreconditionFailed,
  413: ErrorCodes.PayloadTooLarge,
  414: ErrorCodes.UriTooLong,
  415: ErrorCodes.UnsupportedMediaType,
  416: ErrorCodes.RequestedRangeNotSatisfiable,
  417: ErrorCodes.ExpectationFailed,
  418: ErrorCodes.IAmATeapot,
  421: ErrorCodes.Misdirected,
  422: ErrorCodes.UnprocessableEntity,
  424: ErrorCodes.FailedDependency,
  428: ErrorCodes.PreconditionRequired,
  429: ErrorCodes.TooManyRequests,
  500: ErrorCodes.InternalServerError,
  501: ErrorCodes.NotImplemented,
  502: ErrorCodes.BadGateway,
  503: ErrorCodes.ServiceUnavailable,
  504: ErrorCodes.GatewayTimeout,
  505: ErrorCodes.HttpVersionNotSupported,
};
